name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/aws_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "
            cd ~/app || mkdir ~/app && cd ~/app && \
            if [ ! -d .git ]; then git clone https://github.com/${{ github.repository }} .; fi && \
            git pull && \
            echo '${{ secrets.ENV_FILE }}' > .env && \
            npm install && \
            pm2 start index.js --name myapp || pm2 restart myapp
          "
